name: Validate with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26" # v3
      - uses: home-assistant/actions/hassfest@a7c616ce81ccda50150bf1595786c71b1883fabb
